# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 330630f6d73b15fdf97697741ccbb10a55551a03d5a8625b6e67ae14ad0e39eb738d6fcd66a2a992070d8532d344ed2438facfebb527447737d7ed16d05af264

test:
  secret_key_base: 640fc27d61a6dc1cfdc90f618c3d14b4ce0fda3737313ba524cd9d0b322eb031973e420cb201a66bbc2ec8071bf9101f0467c6f271bd2ad14264256478b05548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
